//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;

    public partial class Tag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tag()
        {
            this.Clients = new HashSet<Client>();
        }
    
        public int ID { get; set; }//1
        public string Title { get; set; }//tag1
        public string Color { get; set; }//Red
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients { get; set; }
        public SolidColorBrush colorTag
        {
            get
            {
                SolidColorBrush value = Brushes.Gray;
                Color color = (Color)ColorConverter.ConvertFromString(Color);//Red
                value = new SolidColorBrush(color);
                return value;
            }
        }
    }
}
